### ISSUE TITLE
Actualizacion de Informacion personal

### ISSUE THREAD

**Issue by AnilAgustin** [NAMP-SA/backend-ecommerce-namp#20]
Como cliente, quiero actualizar mi información personal y de contacto para asegurarme de que mis datos están correctos.

Criterios de Aceptación:
- Debe existir un formulario de registro que incluya: nombre, dirección de correo electrónico, dirección, teléfono, contraseña y confirmación de contraseña.
- El correo electrónico debe ser único y validado.
- Después del registro, se debe enviar un correo electrónico de confirmación con un enlace para activar la cuenta.
- Debe existir una sección de "Perfil" donde los clientes puedan ver y editar su información personal.

**Comment by gonzabaldassi** [comment]
- Se corrigieron los métodos para verificar el nombre de usuario y el correo, ya que tenían errores.
- Agregación de hash para la actualización de  contraseña
- Se agregó la opción para cambiar el nombre de usuario y la contraseña
