### ISSUE TITLE
Inicio de Sesion

### ISSUE THREAD

**Issue by AnilAgustin** [NAMP-SA/backend-ecommerce-namp#22]
Como cliente quiero ser capaz de iniciar sesión para poder ingresar y hacer uso de la plataforma.

Criterios de Aceptacion:
- Se debe iniciar con usuario y contraseña especificadas por el cliente cuando creó su cuenta.

**Comment by gonzabaldassi** [comment]
Hay que hacer lo siguiente:
- Revisar los roles
- Completar los datos del usuario, ya que los que pusimos son genericos
- Ver como combinar esta issue con la de register user
